name: Testing Tome

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip globally
        run: python -m pip install --upgrade pip --no-cache-dir
      - name: Install dependencies and run tests in venv
        run: |
          python -m venv venv
          ${{ matrix.os == 'windows-latest' && '.\\venv\\Scripts\\Activate.ps1' || 'source venv/bin/activate' }}
          python -m pip install --upgrade pip --no-cache-dir
          pip install .[dev]
          coverage run -m pytest -v tests/
          coverage report

  docs:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install docs dependencies
        run: pip install .[docs]
      - name: Build documentation
        run: mkdocs build --verbose

  static-analysis:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install tools
        run: pip install ruff vulture bandit[toml] detect-secrets
      - name: Run Ruff
        run: |
          ruff format --check --no-cache || echo "::warning file=Ruff::Formatting issues detected."
      - name: Run Vulture
        run: |
          vulture tome/ || echo "::warning file=Vulture::Potential dead code detected."
      - name: Run Bandit
        run: |
          bandit -c pyproject.toml tome -r -lll || echo "::warning file=Bandit::Security vulnerabilities detected."
      - name: Run Detect-Secrets
        run: |
          detect-secrets -C tome scan || echo "::warning file=Detect-Secrets::Secrets detected."
